CREATE TABLE `tmall_exchanges` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `tenant_code` varchar(10) DEFAULT NULL,
  `shop_code` varchar(20) NOT NULL,
  `tid` bigint(20) DEFAULT NULL,
  `oid` bigint(20) DEFAULT NULL,
  `bought_sku` bigint(20) DEFAULT NULL,
  `buyer_address` varchar(200) DEFAULT NULL,
  `buyer_logistic_name` varchar(60) DEFAULT NULL,
  `buyer_logistic_no` varchar(45) DEFAULT NULL,
  `buyer_name` varchar(50) DEFAULT NULL,
  `buyer_nick` varchar(50) DEFAULT NULL,
  `buyer_phone` varchar(20) DEFAULT NULL,
  `created` datetime NOT NULL,
  `dispute_id` bigint(20) NOT NULL,
  `exchange_sku` bigint(20) NOT NULL,
  `good_status` varchar(45) DEFAULT NULL,
  `modified` datetime NOT NULL,
  `num` int(11) DEFAULT NULL,
  `reason` varchar(100) DEFAULT NULL,
  `seller_logistic_name` varchar(60) DEFAULT NULL,
  `seller_logistic_no` varchar(45) DEFAULT NULL,
  `seller_nick` varchar(60) DEFAULT NULL,
  `status` varchar(45) DEFAULT NULL,
  `time_out` datetime DEFAULT NULL,
  `title` varchar(60) DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `idx_tmall_exchanges_dispute_id` (`dispute_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
