CREATE TABLE `tmall_orders` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `tenant_code` varchar(20) NOT NULL,
  `tmall_trade_id` bigint(20) NOT NULL,
  `shop_code` varchar(10) NOT NULL,
  `adjust_fee` decimal(19,2) DEFAULT NULL,
  `buyer_rate` tinyint(1) DEFAULT NULL,
  `cid` bigint(20) DEFAULT NULL,
  `consign_time` datetime DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `discount_fee` decimal(19,2) DEFAULT NULL,
  `divide_order_fee` decimal(19,2) DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `invoice_no` varchar(50) DEFAULT NULL,
  `is_daixiao` tinyint(1) DEFAULT NULL,
  `logistics_company` varchar(100) DEFAULT NULL,
  `num` int(11) NOT NULL,
  `num_iid` bigint(20) NOT NULL,
  `oid` bigint(20) NOT NULL,
  `outer_iid` varchar(60) DEFAULT NULL,
  `outer_sku_id` varchar(80) DEFAULT NULL,
  `part_mjz_discount` decimal(19,2) DEFAULT NULL,
  `payment` decimal(19,2) DEFAULT NULL,
  `pic_path` varchar(300) DEFAULT NULL,
  `price` decimal(19,2) DEFAULT NULL,
  `refund_id` bigint(20) DEFAULT NULL,
  `refund_status` varchar(50) DEFAULT NULL,
  `seller_rate` tinyint(1) DEFAULT NULL,
  `seller_type` varchar(6) DEFAULT NULL,
  `shipping_type` varchar(15) DEFAULT NULL,
  `sku_id` bigint(20) DEFAULT NULL,
  `sku_properties_name` varchar(120) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `tid` bigint(20) NOT NULL,
  `title` varchar(200) DEFAULT NULL,
  `total_fee` decimal(19,2) DEFAULT NULL,
  `trans_status` varchar(10) DEFAULT '',
  `trans_at` datetime DEFAULT NULL,
  `trans_msg` varchar(400) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_tmall_orders_tmall_trade_id` (`tmall_trade_id`),
  KEY `idx_tmall_orders_tid` (`tid`),
  KEY `idx_tmall_orders_oid` (`oid`),
  KEY `idx_tmall_orders_refund_id` (`refund_id`),
  KEY `idx_tmall_orders_status` (`status`),
  KEY `idx_tmall_orders_end_time` (`end_time`),
  KEY `idx_tmall_orders_consign_time` (`consign_time`),
  KEY `idx_tmall_orders_outer_sku_id` (`outer_sku_id`),
  KEY `idx_tmall_orders_created_shop_trans_status` (`created`,`shop_code`,`trans_status`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
