CREATE TABLE `tmall_trades` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `tenant_code` varchar(20) NOT NULL,
  `shop_code` varchar(10) NOT NULL,
  `adjust_fee` decimal(19,2) DEFAULT NULL,
  `alipay_id` bigint(20) DEFAULT NULL,
  `alipay_no` varchar(30) DEFAULT NULL,
  `buyer_nick` varchar(50) DEFAULT NULL,
  `buyer_obtain_point_fee` bigint(20) DEFAULT NULL,
  `cod_fee` decimal(19,2) DEFAULT NULL,
  `cod_status` varchar(30) DEFAULT NULL,
  `consign_time` datetime DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `discount_fee` decimal(19,2) DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `pay_time` datetime DEFAULT NULL,
  `payment` decimal(19,2) DEFAULT NULL,
  `point_fee` bigint(20) DEFAULT NULL,
  `post_fee` decimal(19,2) DEFAULT NULL,
  `real_point_fee` bigint(20) DEFAULT NULL,
  `received_payment` decimal(19,2) DEFAULT NULL,
  `receiver_address` varchar(200) DEFAULT NULL,
  `receiver_city` varchar(100) DEFAULT NULL,
  `receiver_district` varchar(100) DEFAULT NULL,
  `receiver_mobile` varchar(20) DEFAULT NULL,
  `receiver_name` varchar(100) DEFAULT NULL,
  `receiver_state` varchar(50) DEFAULT NULL,
  `receiver_town` varchar(100) DEFAULT NULL,
  `receiver_zip` varchar(20) DEFAULT NULL,
  `seller_nick` varchar(100) DEFAULT NULL,
  `shipping_type` varchar(50) DEFAULT NULL,
  `sid` varchar(50) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `tid` bigint(20) NOT NULL,
  `title` varchar(100) DEFAULT NULL,
  `total_fee` decimal(19,2) DEFAULT NULL,
  `type` varchar(30) DEFAULT NULL,
  `updated_at` datetime NOT NULL,
  `trans_status` varchar(20) DEFAULT NULL,
  `trans_msg` varchar(200) DEFAULT NULL,
  `trans_at` datetime DEFAULT NULL,
  `isv_not_exist` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_tmall_trades_tid` (`tid`),
  KEY `idx_tmall_trades_modified` (`modified`),
  KEY `idx_tmall_trades_consign_time` (`consign_time`),
  KEY `idx_tmall_trades_shop_code` (`shop_code`),
  KEY `idx_tmall_trades_updated_at` (`updated_at`),
  KEY `idx_tmall_trades_created_shop_trans_status` (`created`,`shop_code`,`trans_status`),
  KEY `idx_tmall_trades_updatedat_shop_transstatus` (`updated_at`,`shop_code`,`trans_status`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


# sample data
# copy and paste sample to db table
#'1', 'sand', 'T001', '0.00', NULL, '202003242200116270145986001', '柠檬草', '0', '0.00', 'NEW_CREATED', '2020-03-24 15:31:51', '2020-03-24 12:59:06', '40.00', '2020-03-31 11:51:14', '2020-03-31 11:51:20', '2020-03-24 12:59:15', '410.49', '0', '0.00', '0', '0.00', '堰*街道**镇堰桥东**号无锡市堰桥', '无锡市', '惠山区', '178********', '马****', '江苏省', '堰桥街道', '150000', 'Sand官方旗舰店', 'express', '1906832066105915242', 'TRADE_CLOSED', '1906832066105915242', 'Sand官方旗舰店', '1298.00', 'fixed', '2020-03-31 14:15:34', '', NULL, NULL, '0'
