CREATE TABLE `sale_record_dtls` (
id bigint(20) NOT NULL AUTO_INCREMENT,
sale_record_id bigint(20) DEFAULT NULL,
order_item_id bigint(20) DEFAULT NULL,
refund_item_id bigint(20) DEFAULT NULL,
brand_id bigint(20) DEFAULT NULL,
brand_code varchar(10) DEFAULT NULL,
product_id bigint(20) DEFAULT NULL,
sku_id bigint(20) DEFAULT NULL,
fee_rate decimal(19,2) DEFAULT NULL,
list_price decimal(19,2) DEFAULT NULL,
sale_price decimal(19,2) DEFAULT NULL,
quantity int DEFAULT NULL,
total_list_price decimal(19,2) DEFAULT NULL,
total_discount_price decimal(19,2) DEFAULT NULL,
total_payment_price decimal(19,2) DEFAULT NULL,
tid bigint(20) NOT NULL,
oid bigint(20) NOT NULL,
refund_id bigint(20) DEFAULT NULL,
trade_created datetime NOT NULL,
received_at datetime DEFAULT NULL,
created_at datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_sale_record_dtls_sale_record_id` (`sale_record_id`),
  KEY `idx_sale_record_dtls_tid` (`tid`),
  KEY `idx_sale_record_dtls_oid` (`oid`),
  KEY `idx_sale_record_dtls_refund_id` (`refund_id`),
  KEY `idx_sale_record_dtls_trade_created` (`trade_created`),
  KEY `idx_sale_record_dtls_received_at` (`received_at`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;