CREATE TABLE `tmall_trades` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `tenant_code` varchar(20) NOT NULL,
  `shop_code` varchar(10) NOT NULL,
  `adjust_fee` decimal(19,2) DEFAULT NULL,
  `alipay_id` bigint(20) DEFAULT NULL,
  `alipay_no` varchar(30) DEFAULT NULL,
  `buyer_nick` varchar(50) DEFAULT NULL,
  `buyer_obtain_point_fee` bigint(20) DEFAULT NULL,
  `cod_fee` decimal(19,2) DEFAULT NULL,
  `cod_status` varchar(30) DEFAULT NULL,
  `consign_time` datetime DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `discount_fee` decimal(19,2) DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `pay_time` datetime DEFAULT NULL,
  `payment` decimal(19,2) DEFAULT NULL,
  `point_fee` bigint(20) DEFAULT NULL,
  `post_fee` decimal(19,2) DEFAULT NULL,
  `real_point_fee` bigint(20) DEFAULT NULL,
  `received_payment` decimal(19,2) DEFAULT NULL,
  `receiver_address` varchar(200) DEFAULT NULL,
  `receiver_city` varchar(100) DEFAULT NULL,
  `receiver_district` varchar(100) DEFAULT NULL,
  `receiver_mobile` varchar(20) DEFAULT NULL,
  `receiver_name` varchar(100) DEFAULT NULL,
  `receiver_state` varchar(50) DEFAULT NULL,
  `receiver_town` varchar(100) DEFAULT NULL,
  `receiver_zip` varchar(20) DEFAULT NULL,
  `seller_nick` varchar(100) DEFAULT NULL,
  `shipping_type` varchar(50) DEFAULT NULL,
  `sid` varchar(50) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `tid` bigint(20) NOT NULL,
  `title` varchar(100) DEFAULT NULL,
  `total_fee` decimal(19,2) DEFAULT NULL,
  `type` varchar(30) DEFAULT NULL,
  `updated_at` datetime NOT NULL,
  `trans_status` varchar(20) DEFAULT NULL,
  `trans_msg` varchar(200) DEFAULT NULL,
  `trans_at` datetime DEFAULT NULL,
  `isv_not_exist` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_tmall_trades_tid` (`tid`),
  KEY `idx_tmall_trades_modified` (`modified`),
  KEY `idx_tmall_trades_consign_time` (`consign_time`),
  KEY `idx_tmall_trades_shop_code` (`shop_code`),
  KEY `idx_tmall_trades_updated_at` (`updated_at`),
  KEY `idx_tmall_trades_created_shop_trans_status` (`created`,`shop_code`,`trans_status`),
  KEY `idx_tmall_trades_updatedat_shop_transstatus` (`updated_at`,`shop_code`,`trans_status`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
